"""empty message

Revision ID: 26be7b7aec69
Revises: 712ae8c5a1a4
Create Date: 2019-08-09 11:53:14.574964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26be7b7aec69'
down_revision = '712ae8c5a1a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comments')
    # ### end Alembic commands ###
